/**
 * Normalize oversized tool call IDs in ModelMessages.
 *
 * OpenAI's Responses API rejects `call_id` values longer than 64 characters.
 * Tool call IDs generated by other providers (or by internal systems) can exceed
 * this limit. This module rewrites them deterministically so that paired
 * tool-call and tool-result parts still match after normalization.
 *
 * Applied request-only — does not mutate persisted history.
 */

import { createHash } from "node:crypto";
import type { ModelMessage } from "ai";

/** OpenAI's maximum allowed length for tool call IDs. */
const MAX_TOOL_CALL_ID_LENGTH = 64;

/**
 * Prefix for normalized IDs so they're recognizable in debug logs.
 * "call_" (5 chars) + 59 chars of hash = 64 chars total.
 */
const NORMALIZED_PREFIX = "call_";
const HASH_LENGTH = MAX_TOOL_CALL_ID_LENGTH - NORMALIZED_PREFIX.length;

/**
 * Deterministically shorten a tool call ID to fit within the 64-char limit.
 * Uses SHA-256 (hex) truncated to fill the available space after the prefix.
 * The same input always produces the same output, so paired tool-call and
 * tool-result parts will agree on the normalized value.
 */
export function shortenToolCallId(id: string): string {
  const hash = createHash("sha256").update(id).digest("hex");
  return `${NORMALIZED_PREFIX}${hash.slice(0, HASH_LENGTH)}`;
}

/**
 * Build a mapping from oversized tool call IDs to their normalized forms.
 * Scans all assistant (tool-call) and tool (tool-result) messages once to
 * collect every ID that exceeds the limit.
 */
function buildIdMapping(messages: ModelMessage[]): Map<string, string> {
  const oversizedIds = new Set<string>();

  for (const msg of messages) {
    if (msg.role === "assistant" && Array.isArray(msg.content)) {
      for (const part of msg.content) {
        if (part.type === "tool-call" && part.toolCallId.length > MAX_TOOL_CALL_ID_LENGTH) {
          oversizedIds.add(part.toolCallId);
        }
      }
    } else if (msg.role === "tool") {
      for (const part of msg.content) {
        if (part.type === "tool-result" && part.toolCallId.length > MAX_TOOL_CALL_ID_LENGTH) {
          oversizedIds.add(part.toolCallId);
        }
      }
    }
  }

  const mapping = new Map<string, string>();
  for (const id of oversizedIds) {
    mapping.set(id, shortenToolCallId(id));
  }
  return mapping;
}

/**
 * Rewrite oversized tool call IDs in the given ModelMessages.
 *
 * Returns a new array (shallow copy) with only the affected parts cloned and
 * rewritten. Messages without oversized IDs are passed through unchanged.
 *
 * This is a request-only transform — it does not mutate the original messages
 * or persisted history.
 */
export function normalizeToolCallIds(messages: ModelMessage[]): ModelMessage[] {
  const mapping = buildIdMapping(messages);
  if (mapping.size === 0) {
    return messages;
  }

  return messages.map((msg): ModelMessage => {
    if (msg.role === "assistant" && Array.isArray(msg.content)) {
      let changed = false;
      const newContent = msg.content.map((part) => {
        if (part.type === "tool-call" && mapping.has(part.toolCallId)) {
          changed = true;
          return { ...part, toolCallId: mapping.get(part.toolCallId)! };
        }
        return part;
      });
      return changed ? { ...msg, content: newContent } : msg;
    }

    if (msg.role === "tool") {
      let changed = false;
      const newContent = msg.content.map((part) => {
        if (part.type === "tool-result" && mapping.has(part.toolCallId)) {
          changed = true;
          return { ...part, toolCallId: mapping.get(part.toolCallId)! };
        }
        return part;
      });
      return changed ? { ...msg, content: newContent } : msg;
    }

    return msg;
  });
}
